version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - mvn --version
  build:
    commands:
      - echo Building the Spring Boot app...
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo Build completed.
      - echo Copying JAR to output directory...
      - mkdir -p output
      - cp target/*.jar output/

artifacts:
  files:
    - output/*.jar
